### ISSUE TITLE
Add controls to toggle layers

### ISSUE THREAD

**Issue by danburzo** [madeincluj/madeincluj#1]
Add ability to show/hide the various layers on the map:
- instagram layer
- street names layer
- buildings layer
- photos layer

**Comment by adriana-saroz** [comment]
Is there going to be a separate map for every time-span ? Or should we treat the time-span as a parameter of the main map ? If we have one single map we need to find a way to pass the time parameter to our custom layers.

I've added a simple layer toggle control and it works fine if we assume that the map is dedicated to one time span. Otherwise we need to override the default behavior and either switch layers according to selected time-span or pass the time-span parameter to our custom layers. We could maybe add each time-span as an option for the control base map parameter (instead of Google/Stamen layers that are currently on the page).

**Comment by danburzo** [comment]
At this moment, I'd say the time spans will only filter the data on-screen, so it would be the same map.
